<?php
/**
 *This is a Morrígan pagecontroller.
 *
 *
 */
 
//Include the essential config-file wich also creates the $morrigan variable with its defaults.
include(__DIR__.'/config.php'); 

// Do it and store it all in variables in the Morrígan container.
$morrigan['title'] = "Redovisning";


$morrigan['main'] = <<<EOD

<h1>Redovisning av kmom07/10: Projekt och Examination</h1>

<article>
    <h2>Allmänt om projektet, problem/lösningar/strul/enkelt/svårt/snabbt/lång tid, etc.</h2>
    <p>Då var jag färdig med projektet. Det är ett par dagar nu tills kursen är slut så jag hoppas verkligen att det går bra. Har även lämnat in alla mina kompletteringar under veckan och håller tummarna och andan tills jag vet att jag har klarat kursen… annars… blir det ingen examen Biblioteks- och informationsvetenskap får mig nu i vår. Men hursomhaver!</p>
    <p>Det har som sagt varit en väldigt orolig och tidspressat tid denna månad och jag har jobbat med projektet samtidigt som jag kompletterade gamla uppgifter, och det är väl det som har varit svårast när jag har arbetat med projektet. Men jag försökte att fokusera och fortsatte ända tills jag är nu färdig med det allra sista kursmomentet för kurspaketet (om inte jag får fler kompletteringar, i vilket fall jag hoppas att jag får veta det snart så att jag hinner fixa till allt innan den 1 februari). Ja, som sagt, jag är lite ängslig just nu. Har mycket att förlora. Men som sagt, jag försökte koncentrera mig på det här projektet och började med att läsa instruktionerna och kraven. Det var mycket som fortfarande var oklart efteråt så jag tittade nog på alla inlämningar på forumet hittills. Vissa kursares inlämningar fick mig att känna mig lugnare, medan andra skrämde mig eftersom jag är långt ifrån deras nivå. Jag bestämde mig för att spela säkert och göra något som vi har redan gjord kursen och som jag tyckte om att göra, vilket blev plugins för lightbox, gallery, och slideshow… eller rättare sagt, jag har skapat en me-sida åt ett påhittat litet företag som gör dessa plugins och fler till mindre eller nya företag och organisationer som är ej vana vid att hantera webbsidor. Dessa plugins är enkla för att även en nästintill pensionerad bibliotekarie ska kunna installera de på bibliotekets hemsida (eller museum, online modeshoppar, bok eller film eller konstsäljare, etc). Jag återgick till min gamla Morrígan med ett nytt utseende (som jag sett hos en kursare på forumet, dock omgjord för att den skulle bli min egen och passa Morrígans vision och image) som passar ett litet, modernt företag med en kvinna i ledningen (ja, jag menar mig), och så här har det gått: </p>

    <h2>Krav k1: Paketera, presentera och produktifiera samt GitHub.</h2>
    <p>Morrígan har en me-sida med en kort introduktion till företaget och våra erbjudanden; en sida som visar upp alla tre plugins och vad de gör, hur de fungerar och vad de kan användas till; en mer djupgående om-sida som berättar mer om företagets tjänster och produkter och varför de är bra; samt en sida om installeringen av dessa plugins med instruktioner och tips på hur man installerar, konfigurerar och använder de på våra kunders egna webbplatser. Källkoden finns GitHub (länk följer nedan, eller i footern om jag glömmer här). Dessa var alla kraven för K1 och Morrígan möter de alla.</p>
    
    <h2>Krav k2: Ha koll på konkurrenterna och lär av dem</h2>
    <p>Jag visste redan innan vad jag ville skulle skilja Morrígans plugins från andra val, och även efter att ha sökt i google om andra som erbjuder dessa plugins, så förstäktes min magkänsla. Vid olika sökningar för alla tre plugins hittade jag sidor vars instruktioner inte ens jag har motivation, tid eller energi att följa. Flera av de webbplatser som jag ville testa krävde att man skulle registrera sig, två (minst) sälja deras plugins som tjänster, och andra hade instruktioner som jag inte tror att vår målgrupp hade kunnat följa eftersom de var lite väl avancerade. Så dessa är vad alla där ute har att välja på, dessa webbplatser och dyra experter. Experter är experter av många anledningar och de behöver självklart också lön att leva på, men vår mål grupp – små eller nya företag och organisationer – har inte råd med dessa, inte än i alla fall. Så vi vill att de ska komma till oss för att få hjälp på traven med att introducera deras verksamhet online, och med nya deras online verksamhet, tills de växer och utvecklas så pass mycket att de själva kan antingen skapa egna plugins eller anställa webbprogrammerare som kan skapa avancerade och specialutformade plugins till deras webbplatser. Morrígan söker att erbjuda sin hjälp till de behövliga, inte att paketera vad vi kan och många behöver och sätta ett pris på det. (Refererar till dessa webbsidor som säljer sådant för att försöka tjäna en snabb slant, ej seriösa webbprogrammerare med rätt motiv! Dessa är svårare att hitta på online (kanske eftersom deras verksamhet är fysisk och de faktiskt bryr sig att möta kunder som behöver deras tjänster) men de existerar.)</p>

    <p><i>I dagsläget</i></p>
    <p>I dagsläget har Morrígan alltså dessa tre produkter, plugins för lightbox, bildgalleri och bildspel. Alla kan använda våra produkter, eftersom det har hela tiden varit grundin för Morrígan, att skapa enkla, flexibla och lätta att installera, anpassa och använda plugins som vemsomhelst som behöver de kan använda dessa gratis tillsvidare. Lightboxen öppnas då man klickar på den utvalda bilden för att få bilden i fokus men behålla sidans innehåll nedsläkt i bakgrunden och granska endast bilden. Galleriet visar en bild i taget (helst ska thumbnails vara mindre än versionen som visas upp när man klickar på en bild). Och bildspelet spelas upp automatiskt, och denna plugin – liksom de två andra - kan användas till så mycket, allt från att visa upp städer, natur, landskap, bostäder, böcker, museiföremål, och kläd eller spel eller filmkollektion. Vad ni än har att erbjuda era kunder! Det går också att istället för att länka till en katalog med bildspel, använda varje bild samt lägga till en länk till bildens sida. Till exempel om bilden visar en annons för graviditetskläder, så kan man lägga till en länk i bilden så att när man klickar på bilden omdirigeras man till sidan med mode för gravida. Vi jobbar i skrivande stund på en sådan plugin och hoppas kunna erbjuda er detta inom en snar framtid! Instruktionerna som medföljer är precis som våra plugins enkla och lätta att följa eftersom de är riktade mot absolut nybörjare med liten till ingen vana som helst med webbprogrammering eller webbdesign, och fungerar med vilket operativsystem,  webbläsare och  utvecklingsmiljö man än använder.  </p>
    
    <p><i>Utvecklingsplan</i></p>
    <p> Vår utvecklingsplan är att bygga smidigare plugins, med fler mindre funktioner som är avändbara, och så småningom bygga hela webbplatser med dessa funktioner i användning som exempel, och sedan göra de tillgängliga för våra klienter, komplett med installationsguider. Vi har alltså inga konkurrenter, eftersom vi delar med oss vad vi kan, när vi kan, med de som behöver oss. Vi tar inte betalt för våra tjänster eftersom det är av rent goodwill vi gör det här (vi har andra jobb) eller har dolda motiv, och det finns ingen annan som kan säga samma sak.</p>
    
    
    <h2>Krav k3: Kvalitet och omfattning</h2>
    <p>Morrígan har utvecklats de flesta dagar och nätter under två veckor, ca 12 timmar i sträck vid varje session (det finns inget annat sätt för mig, när jag fastnar så fastnar jag länge och jag lägger inte av förrän jag har löst något), och är grundat på flera aspekter av det vi har gått igenom tidigare i kursen: lightbox, bildgalleri, bildspel, instruktioner till hur andra kan installera plugins och min Morrígan. Jag vill men har tyvärr inte lagt till så mycket nytt på de sedan kmom03 utan använt de och försökt lägga till lite småändringar här och var, eftersom jag har inte kommit upp i högre kunskapsnivå gällande javaScript. Men jag kommer inte att ge upp, utan kommer fortsätta att lära mig efter den här kursen och efter examen när jag har lite mer tid igen. </p>
    
    <h2>Krav k4, k5, k6: Valbart krav (optionellt)</h2>
    <p>Vad gäller optionella krav så har jag kämpat med de i JavaScript delkursen. Jag har som sagt inte utvecklat mina plugins mer än utseendet. Jag har lagt ner extra kraft på de vanliga kursmomenten men dock ej åstadkommit något avancerat eller fler features utöver det vi har fått lära oss i guiderna, eftersom jag har behövt all tid och kraft för att möta de obligatoriska kraven i JavaScript. Kanske om ett år är jag där, men inte ännu. Jag har som sagt idéer om var jag vill komma med bildspelet (spela och paus funktion, thumbnails, att bilderna är länkar till andra sidor som bilden är annons för, etc.), lightbox (scrolla fram och tillbaks bland bilderna i overlay), galleriet (även här en höger och vänsterknapp, eller också lägga till lightbox i galleriet), dock är jag inte på den kunskapnivån ännu. Men att ha idéer är en bra början.</p>
    
    <h2>Mina tankar kring kursen</h2>
    <p>I helhet har den här kursen varit rolig och innehållsrik och lärorik, men också väldigt svårt. Tyvärr hamnade jag efter i slutet av hösten och hann inte ikapp (skickar ju in mina sista uppgifter endast ett par dagar innan kursen är slut och det är tänkt att allt ska vara godkänt…) så det blev kaka på kaka och jag kände mig säkrast i att följa andras exempel men jag förlitade mig för mycket på det istället för att skapa ett helt me me-sida. Jag antar att jag känner mig fortfarande osäker, särskilt i JavaScript och behöver längre tid för att skapa något jag är nöjd över och känner är på samma nivå som andra. Hade jag haft mer tid så hade jag tagit den tiden men den rinner ut i slutet av den här månaden. Jag tycker ändå att jag har i helhet under kurspaketet fått lära mig så mycket som jag inte visste av lärarna, guiderna, feedbacken och forumet. Jag har inget föbättringsförslag, utan tycker mest att det är tråkigt att jag inte hade mer tid eller råd att inte ha dessa 30 poängen nu, annars tror jag att det hade gynnat mig mer att läsa kurspaketet på halvfart! Jag vill verkligen det, får se hur detta året kommer att bli. Jag har rekommenderat den här kursen till mina bekanta, eftersom det finnas lärorikt och roligt som väntar om man kan i alla fall lite om webbprogrammering. Jag har mest svårt med JavaScript men har verkligen sålt in det för att det är så mycket man kan göra! Även om man har ett annat yrke, det kan vara roligt att sitta när man har tid, göra upp en plan på vad man vill göra, och ta sin tid att hitta till lösningar tills man bestämmer sig att man är nöjd. Helst med en kopp kaffe och chocolate chip cookies bredvid på skrivbordet. Jag ger kursen 7, bara för att det var så svårt för mig, jag uppskattar allt övrigt.</p>    
</article>

EOD;


// Finally, leave it all to the rendering phase of Morrígan.
include(MORRIGAN_THEME_PATH); 